language: ruby
cache: bundler
dist: bionic
sudo: false
services:
  - postgresql
env:
  global:
    - JRUBY_OPTS="-J-Xmx1g"
jdk:
  - openjdk8
rvm:
  - jruby-9.2.14.0
before_install:
  - gem install bundler --version '>2.0'
  - psql -c 'create database sosol_test;' -U postgres
before_script:
  - gem --version
  - bundle exec cap local externals:setup
  - touch config/environments/test_secret.rb
  - cp -v config/database.travis.yml config/database.yml
  - bundle exec rake git:db:canonical:clone
  - bundle exec rake db:migrate
after_failure:
  - curl --upload-file log/test.log https://transfer.sh/test.log | cat && echo
