en:
  welcome:
    index:
      about: "The %{site_name} editor is a web-based, fully audited, version-controlled editing environment originally developed for the papyrological community but designed for applicability to other editing communities. It enables the collaborative editing of texts in a framework of rigorous and transparent peer-review and credit mechanisms and strong editorial oversight."
      access: "To access the editor, please %{link}. If you do not already have an account, signing in will guide you through the sign up process."
      sign_in: sign in
