:agents:
  :eagle:
    :uri_match: "http://www.eagle-network.eu"
    :transformations:
      :CTSIdentifier: "/data/xslt/cts/eagle-xml-perseids.xsl"
      :EpiCTSIdentifier: "/data/xslt/cts/perseids-json-eagle.xsl"
    :controllers:
      edit: "edittext"
    :collections:
      :CTSIdentifier: "pdlepi"
    :type: "mediawiki"
    :api_info:
      :url: "http://www.eagle-network.eu/wiki/api.php"
      :data_format: 
        :get: "xml"
        :post: "json"
      :auth:
        :username: "Perseids"
        :password: "YourPassword"
  :googless:
    :uri_match: "https://docs.google.com/spreadsheet"
    :get_url: "http://spreadsheets.google.com/feeds/list/WORKSHEET_ID/od6/public/values"
    :type: "googless"
    :transformations:
      :OaCiteIdentifier: "/data/xslt/cite/gs_to_oa_cite.xsl"
  :hypothesis:
    :uri_match: "https://hypothes.is"
    :type: "hypothesis"
    :data_mapper: 'HypothesisClient::MapperPrototype::JOTH'
    :collections:
      :OajCiteIdentifier: "urn:cite:perseus:pdljann"
  :cts:
    :uri_match: "^urn:cts:"
    :type: "cts"
    :get_url: "http://cts.perseids.org/api/cts/?request=GetPassage&urn=URN"
    :transformations:
      :OaCiteIdentifier: "/data/xslt/cite/cts5_to_oa_cite.xsl"
  :sample_github:
    :uri_match: "https://github.com/sampleorg/samplerepo"
    :type: "github"
    :post_url: "http://fgh.perseids.org/flask-github-proxy/perseids_sample/push/<PATH>"
    :timeout: 3600
    :client_secret: "YourSecret"
    :log_message: "<ID> Edited by <USER> via Perseids."
  :srophe_processor:
    :uri_match: "http://syriaca.org/"
    :type: "srophe_processor"
    :post_url: "http://wwwb.library.vanderbilt.edu/exist/apps/srophe-admin/modules/services/sosol-pp.xql"
    :apikey: "YourKey"

