development:
  :shibboleth:
    :allowed_clock_drift: 5
    :issuer: sosol.perseids.org
    :assertion_consumer_service_url: "https://sosol-test.perseids.org/sosol/shib/consume"
    :sp_private_key: /etc/ssl/private/private.key
    :idps:
      tufts:
        :issuer: sosol-test.perseids.org
        #:entity_id: "https://shibidp-test.uit.tufts.edu/idp/shibboleth"
        :entity_id: "https://sosol-test-idp.perseids.org/shibboleth"
        :display_name: "Tufts University"
        :logo: "tuftsidplogo.jpg"
        :sp_cert: /etc/ssl/certs/sosol-test.perseids.pem
        :idp_cert: <%= Rails.root %>/data/certificates/idptest.crt
        #:idp_cert_fingerprint: "FD:9D:EE:17:B3:C5:F9:A2:B9:A6:8A:93:11:5B:1F:CD:2F:A1:25:5F"
        :idp_cert_fingerprint: "56:87:1C:52:43:44:22:C8:C1:26:87:E5:8E:FC:CB:55:CB:0D:D2:AF"
        :idp_cert_fingerprint_algorithm: "http://www.w3.org/2000/09/xmldsig#sha1"
        :idp_sso_target_url: "https://sosol-test-idp.perseids.org:8443/idp/profile/SAML2/Unsolicited/SSO?providerId=sosol-test.perseids.org"
        :idp_aqr_target_url: "https://sosol-test-idp.perseids.org:8443/idp/profile/SAML2/SOAP/AttributeQuery?providerId=sosol-test.perseids.org"
        :name_identifier_format: "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
        #:authn_context: "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
        :authn_context: "urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocol"
        :attributes:
          :display_id: "urn:oid:1.3.6.1.4.1.5923.1.1.1.6"        
      ulei:
        :issuer: "http://sosol.perseids.org/"
        :entity_id: "https://aai.rz.uni-leipzig.de/idp/shibboleth"
        :display_name: "University of Leipzig"
        :logo: "uleipzig_small.gif"
        :sp_cert: /etc/ssl/certs/sosol_perseids_org_cert.cer
        :idp_cert: <%= Rails.root %>/data/certificates/ulei.d.crt
        :idp_sso_target_url: "https://aai.rz.uni-leipzig.de/idp/profile/SAML2/Unsolicited/SSO?providerId=http://sosol.perseids.org/"
        :idp_aqr_target_url: "https://aai.rz.uni-leipzig.de:8443/idp/profile/SAML2/SOAP/AttributeQuery?providerId=http://sosol.perseids.org/"
        :name_identifier_format: "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
        :authn_context: "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
        :attributes:
          :display_id: "urn:oid:1.3.6.1.4.1.5923.1.1.1.6"        
test:
  :shibboleth:
    :allowed_clock_drift: 5
    :issuer: sosol.perseids.org
    :assertion_consumer_service_url: "https://sosol-test.perseids.org/sosol/shib/consume"
    :sp_private_key: /etc/ssl/private/private.key
    :idps:
      tufts:
        :entity_id: "https://shibidp-test.uit.tufts.edu/idp/shibboleth"
        :display_name: "Tufts University"
        :logo: "tuftsidplogo.jpg"
        :sp_cert: /etc/ssl/certs/perseidsshibcert.pem
        :idp_cert: <%= Rails.root %>/data/certificates/tuftstest.crt
        :idp_sso_target_url: "https://shibidp-test.uit.tufts.edu:8443/idp/profile/SAML2/Unsolicited/SSO?providerId=sosol.perseids.org"
        :idp_aqr_target_url: "https://shibidp-test.uit.tufts.edu:8443/idp/profile/SAML2/SOAP/AttributeQuery?providerId=sosol.perseids.org"
        :name_identifier_format: "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
        :authn_context: "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
        :attributes:
          :display_id: "urn:oid:1.3.6.1.4.1.5923.1.1.1.6"      
production:
  :shibboleth:
    :allowed_clock_drift: 5
    :issuer: sosol.perseids.org
    :assertion_consumer_service_url: "https://sosol.perseids.org/sosol/shib/consume"
    :sp_private_key: /etc/ssl/private/private.key
    :idps:
      tufts:
        :entity_id: "https://shib-idp.tufts.edu/idp/shibboleth"
        :display_name: "Tufts University"
        :logo: "tuftsidplogo.jpg"
        :sp_cert: /etc/ssl/certs/perseidsshibcert.pem
        :idp_cert: /etc/ssl/certs/tuftsprod.crt
        :idp_sso_target_url: "https://shib-idp.tufts.edu/idp/profile/SAML2/Unsolicited/SSO?providerId=sosol.perseids.org"
        :idp_aqr_target_url: "https://shib-idp.tufts.edu:8443/idp/profile/SAML2/SOAP/AttributeQuery?providerId=sosol.perseids.org"
        :name_identifier_format: "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
        :authn_context: "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport"
        :attributes:
          :display_id: "urn:oid:1.3.6.1.4.1.5923.1.1.1.6"        
